// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtvJWs9NFdG_SYaejk_cZyz79IcY33d9o',
    appId: '1:1059660678739:web:020a0312e8516afa3268a6',
    messagingSenderId: '1059660678739',
    projectId: 'smartclasssync-49c87',
    authDomain: 'smartclasssync-49c87.firebaseapp.com',
    storageBucket: 'smartclasssync-49c87.firebasestorage.app',
    measurementId: 'G-54607FNN0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIiLDM562AFp1MN-_vGk6YuX6OsWASMQ0',
    appId: '1:1059660678739:android:63caa523a772d3293268a6',
    messagingSenderId: '1059660678739',
    projectId: 'smartclasssync-49c87',
    storageBucket: 'smartclasssync-49c87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXQ-NafMUh5Dr4rrYa4FEooRL5ZRm3R8',
    appId: '1:1059660678739:ios:c8c6898f94f97f853268a6',
    messagingSenderId: '1059660678739',
    projectId: 'smartclasssync-49c87',
    storageBucket: 'smartclasssync-49c87.firebasestorage.app',
    iosBundleId: 'com.example.smartClassSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXQ-NafMUh5Dr4rrYa4FEooRL5ZRm3R8',
    appId: '1:1059660678739:ios:c8c6898f94f97f853268a6',
    messagingSenderId: '1059660678739',
    projectId: 'smartclasssync-49c87',
    storageBucket: 'smartclasssync-49c87.firebasestorage.app',
    iosBundleId: 'com.example.smartClassSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtvJWs9NFdG_SYaejk_cZyz79IcY33d9o',
    appId: '1:1059660678739:web:1a1eb0f5439951ae3268a6',
    messagingSenderId: '1059660678739',
    projectId: 'smartclasssync-49c87',
    authDomain: 'smartclasssync-49c87.firebaseapp.com',
    storageBucket: 'smartclasssync-49c87.firebasestorage.app',
    measurementId: 'G-48W5C85BRD',
  );

}